apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - ./kustomizations/repositories.yaml

  - ./kustomizations/metrics-server.yaml
  - ./kustomizations/cilium.yaml
  - ./kustomizations/cilium-config.yaml
  - ./kustomizations/longhorn.yaml
  - ./kustomizations/nfs-csi.yaml
  - ./kustomizations/cnpg.yaml
  - ./kustomizations/cert-manager.yaml
  - ./kustomizations/cluster-issuer.yaml
  - ./kustomizations/gateway.yaml
  - ./kustomizations/gateway-config.yaml
  - ./kustomizations/private-bin.yaml
  - ./kustomizations/cloudflared.yaml
  - ./kustomizations/authentik.yaml
  - ./kustomizations/jellyfin.yaml
  - ./kustomizations/radarr.yaml
  - ./kustomizations/sonarr.yaml
