apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - ./kustomizations/repositories.yaml

  - ./kustomizations/cert-manager.yaml
  - ./kustomizations/cluster-issuer.yaml
  - ./kustomizations/gateway.yaml
