apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:pfkZp44kFEzfEFNbW9njMDbCU+0XeIcTdPpYLRhAXEx8RUrlwEJAJwAI+ooV1pK+eqrRbOR73ho=,iv:HHvjcD/yUkrb6o/vzY5Y1wP+9aDWWiICAoh/0pLA4V0=,tag:vWQiohLnddfEMv8O11eR/w==,type:str]
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: cert-manager-issuer
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-19T12:00:58Z"
    mac: ENC[AES256_GCM,data:lCbimeYsHbz+1y7QXFqHsfyATqx6RIETWLMhdqzl8t7pOcLL1KqPqzS6gDTF/mtXCSuSH9U1g1pn8smktK1B2NpqG/KwC9lWCoMlBLnOzeXAD3xly4elj0aXpsmZ02zQNQVOG5u2qsPa9mHeBD1OBDDkJCSBAI/JPgp4lwvjWbw=,iv:HKUR+WgWaEDvLo08icLRcpKaDIVsWR7q2R6qe3zXdT0=,tag:Y1gWPVd1MU4X/G6yEr7ZGw==,type:str]
    pgp:
        - created_at: "2026-07-19T12:00:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA3D6UhZegt8OU82jZscT03GJmeKgmNS90A+Eu+ppt4Hsw
            FP2Ny4hRbLuTuXsBJCJh5xHKmj9OsZPACLr99NZ23ik8yPtMZXGAOInKofcZNr3F
            1GgBCQIQDuBJPpbtJ5XZa0hZuueBa2teM9V88UCpLLG+OiuE6QTvUKjHOtsvT7yY
            wyXanh0NMp6o/6qCbnLijhAoU/Z2N93tq7Pn52DEzSMdx9VNlCiwYQojOWn3JRJ0
            cRmQ5c8e4GcNCA==
            =w82x
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
