apiVersion: v1
kind: Secret
metadata:
    name: wireguard-config
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:RyCMW51/qLjm+NWekzESBjOHm9RfulaPbdAr5qwtfPiMa43CC9TpeS3hKuf1dJK79xcyE/a14XPK7rzgC4qto+9lcWfNXf14XT5bBioQkktS+gdcbq7Gii9hsLuuLbhb7eCPHGWAnjyMWcpWhh9DRfJXsMWUUoBzn5N1B3LUqGCJ1kYqmx1CoSOP1tvDB8+lR4iitBOtQwogScixRAYizaStmoDBiBIsFfthjifOHdbMPKUKkLgIHkyxLwDVt46P1+Y04bRcUyS6sNxFP7jQKc+jN122BBC8OT0bSTgo9Wk5o8h2yA2qdRrm1QDkoCpbNf84XQ==,iv:csU+CMeya7wXWmoJGhLlIitATuMZHqUn72V4LXx4cFg=,tag:SONRrINhrzhtY/g92qkPAw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-26T17:23:28Z"
    mac: ENC[AES256_GCM,data:KhX90k1dA92D9w6KusYFJKFcVXPk1CGFZYSPX/smrOi9WhdkYL+npuna+NglADtWqHJdeJaaDwSs87Q/YwtLVJr0BIWQ1qjWlNcOD7MB0SwJ4xE7gbNhsYPuigepOqnGNMKb4BVydSYfmHaJkgo9vz+BqGKVLPCYG76P4N2VABU=,iv:hR1vMluhRzJiYsyKzIElY4/1X75t/Ry0SF3hjBmp7Uo=,tag:GcGSx2drhHzYfsgvS9/Vdw==,type:str]
    pgp:
        - created_at: "2026-07-26T17:23:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdArulPHmcxa8TJHSSHw0mC7l+TA4pyjRu6S7OsufANT1Uw
            cStnQJqdlAOrKRlqCU+4HfQ5wKUoIdQWws55zchI+ryTbKBuRLzWl/i/4+vVHDk1
            1GgBCQIQ40w+OaUvgY8L8cm838IeH8jS8OzFcFaTLD8aec+2C29dB5yGAhwQ33WO
            QzzVNPobzHRiYkWrd7ustHBUUK0tdWArmY/vBvYN+rdNtypGWpxhiFI3DG7CVmk9
            8pCu72os0ElDsg==
            =Np87
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
