machine:
  network:
    interfaces:
      - interface: ens18
        addresses:
          - 192.168.1.206/24
        dhcp: false
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.254
    nameservers:
      - 192.168.1.253
      - 1.1.1.1
      - 1.0.0.1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-cp2
