---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellystat-backup
spec:
  storageClassName: longhorn-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
