apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:xfUvC/zdp1U1J8AkOYaZK6Q0QEwkVklF0vgCfs5qsgzaAZanWESTHeudccDKN0v+YQiEWMA/YOitcEppGNSfKEzXJFXn+hEdf7qL88DHrNcf8wI8mwkF9dD8lZOB8ti7zA84k4v7qitsO1c9kKOOp30I/HbGAZWz/UAJYs/pV9jDtDw7AL9MWdn9AtoBbPV6HSKX4LPnqJ2pLx8NymEsFLpeB04wVCx1XfVs7Eu/Ejs=,iv:SHHQ5/PY9nlKsriUH1M3EJdHKe86jjEMQ+BaMURDV+k=,tag:/MvgM3AsyvNheDRP1j7+ng==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-18T17:21:59Z"
    mac: ENC[AES256_GCM,data:kZ/a9scxpW4bbmtx4QDb2tP01l003ktLH9X1kFXHUy4G1aAulDt5RPB2OtGmudO1IWq48xrogOYnVuuD3kiYzdmpJIi05Fpnql/8+pjONRbcy6ozK2JoutPVBBrbUZxOuWOA6Itb5P9YZ4RAvpXoNluooL7rG69VzsN5OrJ9Znw=,iv:Vdo6RxQL9za0ikaybHgJEQByyj0KoDCwwTcvkUAXtfE=,tag:FeA83gs6T+Lg0xCVCanIgQ==,type:str]
    pgp:
        - created_at: "2026-07-18T17:21:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAeXbuFXYkBYTI3FKQFCKC/cI8LAc9rRjjATM4ZIy9uFkw
            mfTX+ADG/8gmW7F7aiCdsZe2mEcQNCkjlb1XSJ37ZmexqJVUiDqIVVYafsDyAQTH
            1GgBCQIQlNrP8uokFIueLcnvIB47rWJ5cYBVmIBTT3uukGlzBp77Mgz/wnb3LINj
            Fjzcn9msaunzTTy7QNQ8IXeQkmM0Op+rl3fPNCxozTvriw4He/GynWYYug963fGO
            G67pU0toMbj2kg==
            =aBNc
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
