apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres-s3-backup
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:xUSOJIeWP6csxuc3xidftW1KXgogJM2viI4W9F59BkY=,iv:7tZhS45aDMuYVLHKD3UuyXu1qInTNHMR9ZwTNqjwVh8=,tag:ifHnlGpI8sTZwuGHmcmUyA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:qdEh8b09GmKqzmbC97OkB1Gytb4TMrq57b+j1kmdm4s=,iv:tzeTtbyIBYHEV62JMXSTsBSiNXiJtOi0jCMXc7KhmfA=,tag:tg9MDLMIaYkWHD69O5oRFw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-20T12:54:14Z"
    mac: ENC[AES256_GCM,data:rUm3ElCXsfEV5Qo6mNujC/JE7sziVy/9nrCf/wIxYax1Z4ZxRhR1Xlec7CgT0beyjRZWibezvWe8SnLQBQkyvcZcJdiNBlQ+Xs7RTnYLMRYkr2cW+FHpOTnMYyv4ta+qJcWsqYVZ7vu82hy5GFJoZUI5+Ubdup4cIkBJ3GHFbKk=,iv:sj1YsZUFFtCMYzdQDpCoKg1FZcOEEKBjYsYM3WZsgA8=,tag:86pELvdZa5Fgr7F70Hzh7w==,type:str]
    pgp:
        - created_at: "2026-09-20T12:54:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdARsCYHuNARJi/ZN/WjIMnRii12rTJfjQyoEAy7Gt7Gkow
            6fvmPkW2hCFKEIfEiswkoX61UfSecahJftpbBpvl0whGyXWP9X6KWynSHAk4ivvv
            1GgBCQIQ2V542su4oh5A2QEeY11g6tq2f6B/rrnQ90pj0Uy/GPaw3ue3QgYUkhGS
            B51OzAPXBwMqYT0h8ovIKCT1hi/l81OmJVhPQRmZq4MRXWFqtEmrtlvaht2ImUOQ
            C0LZypLccTGgCA==
            =M4p5
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
