apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:iMWqDg+yqyUlM/fTSQvpvpmpy1T1UW4ogjvGK960wjJyuq0zUzmU1sPjKm+K413UQJAO6YBcKLZrpBtwIErdbSP55lISeOhlE/uCc0zmay2SmPJoaR5QhzqTH8KHlXHam+V5Gw==,iv:7iOTwa7SNneFtuHaIfiMhlmG05NuYqxjcgS+JmZ6ihw=,tag:orfx6oxlFp1tHr6umdKwLA==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:HkdGAZBkqYzZasBcUKYUYSANozBb2l+d9jEVlMJrN5IJ+fL42QZ9Y+J/cJChlMINmtd6Lu6j9XezMyAIAwnkYQ==,iv:65kFLoRELM+w7giu/61EbEmHRCdoTjZefl2E4FfgsGY=,tag:RAcqMDSInICPXEYjGdkYvQ==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:22marTLun5Dd97F59nxEAnQfFQcbUWUR2FqCTplwIyY=,iv:841SFAz5IkepO5Q1djFYSgudV113l78AQhdtPJtbIPg=,tag:Pe2ugL5k2Gfk4h9lz2kqlg==,type:str]
    smtp-password: ENC[AES256_GCM,data:t2E96nCFtqK2t22YNM1oTfj/jfQ=,iv:lkyQB7ZF3lELXmGvjOcu70kA9F7HqEkfYF3JAvjKsg4=,tag:58KJX0/ygYJ2SDLD9j5AhA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-19T16:17:48Z"
    mac: ENC[AES256_GCM,data:701yZXd/cpPjcdjfK+qcnA8YmKE5XvhRzbu4BZ3lxuEiBWOboaSCI1C9hfzPkul8FrU6J4PkcdgfY1DHoUNu7FZGA1z01DOWrPHDFl9DF4dizjAH88+3kv4xQItKOuY+iHhgBYQYn9yxiPF7zHWT1h58eHC7GFZIy0fPlnDH4mo=,iv:x+AI7WZoVCsyaQX8ueSDSd23iVIcXf27/4hVay8J0VQ=,tag:eBQbUQ/MgsfYzmbHX9wp7A==,type:str]
    pgp:
        - created_at: "2026-07-19T16:17:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA5hOb41VJWqqbQMylMxttzBwkUi9qaDLwaFdbkiMWFiww
            GUBotDWKR7lTZki27ennvCnIrDd2HxfhNjemJtqa8x/evZc+uGZ96qLNSamuAqVe
            1GgBCQIQMfwvzPphki7eeRBIq+dSN1/TCy8/6Bm8e0Vsct3jIZ3nv86GvFZL+kYW
            aj9fqHTnFLYiPx/HLxPPO4XT9453ojicUPQKsXp9s3hxKU0S5FE/4moBYCFVcQZH
            69ymgrY0BMDcQw==
            =BoAV
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
