apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:Lu51Ad3T2NzhYLLoJt+jknDI14Dkfbf1jfdklQQVzZ2cUOl4ZawTf5TAVFyOwVMa+9UVhCD4Oe02lTQYwLA+/F+mwmmPSkK7C6GMdCC/FcmtMh7ZfWaZrCskrm0IC1XDQDiMlQ==,iv:TMzQY7k76KLnZYVCVBQ+ET/m/v6kOUS27uzn1pOUrQw=,tag:x9V+35jsChXPZng3TNJcqw==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:labsMsjVgbcM/gRnMHh2slO026t86Rbg9RBoViNzDr6IudtZy/0Xr6RXKF2+u2gBnNZYOAZOJE4tAvRVKcrq3Q==,iv:Jv9Z+Nwkyv/dyeMD2Oumvy7bFQoSwunhnwzsiP0rKuY=,tag:nbLCl6x4AkB65SiG2nFPOw==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:42Ut8CSX1gYwhIlIcLPZ9fuMV8Xei9ZWSaDbwu/BtdI=,iv:ZLkVgy4Ko6HNF2BqxgI+g49N0nKo12jJ6IiPViIBv9o=,tag:hnj6Qu29dFBRwBzfzZHOWQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-19T11:28:24Z"
    mac: ENC[AES256_GCM,data:TOmjLtoVrCwCZEI+URyceeB2jAsSXaZZUnfUtZ7KQZyVbtiKKp6AYvaBzBs+ebGMcQa5Nx6l4VUutUzzN8oQd0kWCsRzjTVtonhVg1oWWfULj9Au6oYZvD2WRSCWCl7Jpk/cnjh1EkCXkNC652RIbcgD2S4jvJwZAvW/bZZWplw=,iv:rMkyMUQHv7MukPXh7A8ulNSHGgBdIw0Hvcd9JNqnB1U=,tag:uSBYNkr/8ngOmd3hnUXuww==,type:str]
    pgp:
        - created_at: "2026-07-19T11:28:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAJzdqtcU4CIpR/gV4ZeDaDEE9E6sM9txsKswTtL384VIw
            OcR5rm3TQjGkPus3HdSTl4OT365u3kLl/nW7CEVxX26b0IV+Q02Navb5MgCHV1Wg
            1GgBCQIQjvt82Q+bYdBhQERLPuaVoL1mPj3OZypOu51x9IrGHK+74ajT9w2Anzkg
            R1lBMT9zrwEaR/h6AhfWiVLCpg/9A/qk7GWbQbBpF223w8a/bdQ7i6oDBXw67u5h
            Am+0yJA2m9JnmQ==
            =LqzB
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
