---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  storageClassName: longhorn-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
