apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:xr3x8iR1DCSxeUZM+pKf5uW+k1uN1uct08gsQyZTPFo=,iv:YNp2B2VK90hENMv7iSBeqtO0ZmNB6abYkAJuUpH41zE=,tag:Ip0lEjMP8iox+ZqAjg42Kg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-22T15:10:50Z"
    mac: ENC[AES256_GCM,data:rVHPlnnJiIxgnrEFDoiRhJaW9eukIqv5R41Mc92EwhpLSoEROkZq5ckfEn7sB2Wp1E1dv4IAST8eh90JZ3NNB42rI9/rAUJnaPN6JPGGUNOMX1DB+c+LZzLEz782ChjTf5HLl3wrimaMyAjPcO+YntLwdsCdSHAeOY2Rp4GDvSs=,iv:201Vf+1OgnJbHlbet+1F/acBu/L6Urk0QXYMsTBOme0=,tag:crJ3HBcVoTgHoD5Qo6BNiA==,type:str]
    pgp:
        - created_at: "2026-07-22T15:10:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAsolzNqK1CScn5Dvl1tupWziX6geTgLkYnw3WeQBQFiAw
            uNgOk3xPl0O54dnZi5hNZ6Io6cb0IyWDe4tc43Z9uWYzCcng80onK0oUF+8zquf3
            1GgBCQIQkHFRiYvyl//w2UcdWeJy0mI3RuLdPTurWRwRbl4YxYOvv6B/MkA9jpKx
            GKeecyy59/xXi7VKRXI55Fp6hq8qzuOI2wk8ooevMhA6Rr/VAJgNyIaNvc7a+DO2
            +NRxIAWlcNhieg==
            =4nn9
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
