apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

resources:
  - namespace.yaml
  - media-pv.yaml
  - media-pvc.yaml
  - config-pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - block-metrics-filter.yaml
  - qbittorrent-secret-sops.yaml
  - qbittorrent-config-pvc.yaml
  - qbittorrent-deployment.yaml
  - qbittorrent-service.yaml
