apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn-credentials
type: Opaque
stringData:
    #ENC[AES256_GCM,data:alJWA4Ot95hpkgoW4pj9DqMCvnUgbRiKAjDSRByAzag9nngYvV2O3C5CFmlLIJ0S6nB48wYq/5IGt8Ne4CdAItrS+1fmS3Pe+A==,iv:UOXas64tGNxd9/w9iWZWmpoIaZWmPSm0e2SJ2ZINhbo=,tag:r8tyLx0O5LhIfeEJr/RgHg==,type:comment]
    #ENC[AES256_GCM,data:we7piYzpilkW8moJBoR+F5cumjh7E+OTzF4lHqh8Myi6xk8LQd0RFI1zKM+AhgZX58Pavs2/wzAB3VK43n9EH0MQT9VnfuKG7rdt7GKOi1DsEkqdg0UtmPXJrnM=,iv:xRjwDb92ZYP3IxIqDlBXIG/9JzjlG41+LXqDrzOxvro=,tag:upRZU+lnlmGz22EyhMMm6A==,type:comment]
    openvpn-user: ENC[AES256_GCM,data:cp0JabUr/eOKFQIH99Ryf8RfTw8zfH67,iv:aBZdKVRZM9dOG5kEHvUTweicP9pgxwEkoNz1NxM9lfk=,tag:+3cn4xYyih/TNj5GxgVsgQ==,type:str]
    openvpn-password: ENC[AES256_GCM,data:QGWm7PdJHogXoV9oYFN759ys/S+fRNyV,iv:Nig7qkRhJdLuAMg9CF0uMYAhAbzoDmhvqzUFrXVNl8g=,tag:+3/KE6T8HDtduBr4PFv8mA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-29T15:52:39Z"
    mac: ENC[AES256_GCM,data:QSHfOb2B4nS9cIATwnDjFgXEczW2raYi8Mps9BOaWUN1eiNTeSOtjrDQu079gsl+fH1UPNS66mP9KWc23jWIbwhd7DrH/VeXMOnhQJbbegxf+836guGusd4LSYKEgEsIk7y+UU4/OOTUpWLUt5vh+MWk4Pk45ulYoIIE2aDWVAY=,iv:+h1R2eoYUSdKYv3EA99Lg/q3uRRdq5vhMadyg/0SPZA=,tag:0BsB06CmNvVzQnPTDqtwjQ==,type:str]
    pgp:
        - created_at: "2026-07-29T15:52:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdALdb3WRFGnyvCtdJ9/Sj84Awb05PkEgJpolNv8VujpSww
            CI4A4lkuSa+z8lBWj7GGZBKv7OpRnce2ccH5OGpx5ZUq3gWQFBpn8C64OxHKCcBk
            1GgBCQIQudkClTjxsz9R72AYh2ZzJnMFVOqxLRCsK3FkyY+q2RlG2bg8CyZkrrUc
            y187kdDo3ca2b2YrxwvONN7aswbus5OfHiH0NT+VW1CwjrUdApj5e8agUQWbTf2g
            2iuxC1QefqXPEg==
            =qyMe
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
