---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Jellyfin
    gethomepage.dev/description: Media server
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/pod-selector: "app=jellyfin"
    gethomepage.dev/widget.type: jellyfin
    gethomepage.dev/widget.url: http://jellyfin.jellyfin.svc.cluster.local
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_JELLYFIN_APIKEY}}"
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - "jellyfin.nstnr.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /metrics
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: HTTPRouteFilter
            name: block-metrics
    - backendRefs:
        - group: ""
          kind: Service
          name: jellyfin
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
