apiVersion: v1
kind: Secret
metadata:
    name: general-postgres-s3-backup
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:jsWtt4hpO98LfQegJS9ASeFwu9/7GcVjx8a8EH/kkwI=,iv:GnaTc+pxF+OKivkBybrNzaF5CJnfzJyUxX8CVRDbaUc=,tag:Fr/5MIBLUAZE58YGaS+l6g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:bCW+YntP3asnKEwpdYenRrTqZfmoTO/HRIvtS08Aggc=,iv:7we7uhLbmGW+coJ5MRbw98efsobg+qkRrnXSzOs6jsk=,tag:hupBYkGwXIU2JKEL5FMp+g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-20T12:54:14Z"
    mac: ENC[AES256_GCM,data:GCGPDJJ/ghQkAVWg7+tLxMIpyyHQaoYmTbsInFOMA1TFu/5WTnIUG7tEFHBD29LTBG1GukhTMzPDXHWEULbAV1wsq3rjI9d4Jc5nNxgpLdHSTxqBNzzYN1XoXtkYc8E9hHzJEfyb8v3f4qxqakbZDbu8UdnhBpSSuJyF0zzGj1E=,iv:WwN8loBUhuai7v3wY4vsotMoBz9ge/9lQuEoxTQpgCI=,tag:A7/XGVHlmD2AK7nRGIa0rw==,type:str]
    pgp:
        - created_at: "2026-09-20T12:54:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAek5smMS1qzWPB67qP3GZlpB2jFWaxCVTA4h3VwOUmSww
            e/D9X/1H4g4TIPts33G6+/61/YJhsIhPkKPn5qzR/eDqcfqweWgSutmCcwqeuQ1W
            1GgBCQIQP3dPRYihb9LyranobYcMxxjyoqOHZfEl2ch9GfAJ6fiNVKw9c64TlJCP
            /ojTntEZjjOFEXQkgZ6VEpSRCjJiWx/oJpaEvPAfrFqxRgCP6HquURQo0svXoBt8
            bbjMTpl0hFMebg==
            =7ucI
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
