apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tRHhAaLW,iv:xpd8MQfJNVOKwfMg81xINu7K/WClad3Nc9FWIduwlXY=,tag:+NzgSrhq9d2lbK8Juf97dQ==,type:str]
    password: ENC[AES256_GCM,data:iKDih3lDplFmSuibeRjkEKqIw7xachGs2gMo9sZETZE=,iv:U5dPga/cB86AB4oTSl75U2zS1WeeUKFrl0nx1oAg/UI=,tag:72cGX3znKgVvgaXPwcLrqQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-01T20:47:29Z"
    mac: ENC[AES256_GCM,data:ImN6ZooIYAERfeIv9bsEllasw2wSlk5GIwS03o2ETkXVw7igL7VT6zqMyJKX14TziHpn7NTUROrfxH56TgBctA8m4x+YGDu/duE/DJYCEE9Fm5xuDPiG4iWcqlEPyOOsr394NSVGVK1ygaRgAYF7HAoMvUZoUiWkoqB7bNPADPs=,iv:OkhBezdkMKUAxsO1cPt2vU9IFRwmiMKv0jh18JQgCrs=,tag:hPRe+HT/K9b3tM2qxFcaLg==,type:str]
    pgp:
        - created_at: "2026-09-01T20:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA5Atcb9kxMuUzHDK4iaz8YpYC3xPAmTjqWiCcuAvVgHgw
            hAEbgG3U0pBuOZ3wBQ4F1EfqXmM69I0T7wNgwT7V96CHngr2ht1Sz0lD6IngWQJN
            1GgBCQIQFJtE8WvDgbwlue1wGVXpxlSIP2qUu2jDGJGoIuhJGPPkPRMFmB3zCEjT
            sgXTy/U1jrKV3fWqEZfu3kCD3VM8FJjDqTnrNoyX5e4BnWzaYy9b4e7cDYrYf0na
            V0hjKXjPfnfZNA==
            =+y5Z
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:KEcyd5Rt,iv:2URLON9aWAzbeJ+Hwe2z/agL5esWdEPiI/TSmtZIJ+I=,tag:kTdACy8HOFFtX3XT3YcNpg==,type:str]
    password: ENC[AES256_GCM,data:u4H4g5CuJg3QuV2MYI+YAIrvSKjTYyPI96XI6xm3KAk=,iv:OQ2IdeV0gfu7SGCvsVeF3ytcZ1V7z1lAzIMuzWXs9wg=,tag:oJ6E6gBhsYf2X6Bmvqj99w==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-01T20:47:29Z"
    mac: ENC[AES256_GCM,data:ImN6ZooIYAERfeIv9bsEllasw2wSlk5GIwS03o2ETkXVw7igL7VT6zqMyJKX14TziHpn7NTUROrfxH56TgBctA8m4x+YGDu/duE/DJYCEE9Fm5xuDPiG4iWcqlEPyOOsr394NSVGVK1ygaRgAYF7HAoMvUZoUiWkoqB7bNPADPs=,iv:OkhBezdkMKUAxsO1cPt2vU9IFRwmiMKv0jh18JQgCrs=,tag:hPRe+HT/K9b3tM2qxFcaLg==,type:str]
    pgp:
        - created_at: "2026-09-01T20:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA5Atcb9kxMuUzHDK4iaz8YpYC3xPAmTjqWiCcuAvVgHgw
            hAEbgG3U0pBuOZ3wBQ4F1EfqXmM69I0T7wNgwT7V96CHngr2ht1Sz0lD6IngWQJN
            1GgBCQIQFJtE8WvDgbwlue1wGVXpxlSIP2qUu2jDGJGoIuhJGPPkPRMFmB3zCEjT
            sgXTy/U1jrKV3fWqEZfu3kCD3VM8FJjDqTnrNoyX5e4BnWzaYy9b4e7cDYrYf0na
            V0hjKXjPfnfZNA==
            =+y5Z
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0KmUK+w=,iv:yZaJLgXLPAtIZfDgHAtwjZTVZsyq2DsnKybQ8U11Bps=,tag:/CW5l55lf1LxPgCGylHs+Q==,type:str]
    password: ENC[AES256_GCM,data:FaECZ4PCjrlqNy5N3hexSAbhXdeFOrOvQvjw8xaUD5M=,iv:EwInKFDjuj2OcUEFC0xal539E/m+/7ZnR3nBAMOSLzM=,tag:ttMCOCwZOTjDDxhgZxsawA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-01T20:47:29Z"
    mac: ENC[AES256_GCM,data:ImN6ZooIYAERfeIv9bsEllasw2wSlk5GIwS03o2ETkXVw7igL7VT6zqMyJKX14TziHpn7NTUROrfxH56TgBctA8m4x+YGDu/duE/DJYCEE9Fm5xuDPiG4iWcqlEPyOOsr394NSVGVK1ygaRgAYF7HAoMvUZoUiWkoqB7bNPADPs=,iv:OkhBezdkMKUAxsO1cPt2vU9IFRwmiMKv0jh18JQgCrs=,tag:hPRe+HT/K9b3tM2qxFcaLg==,type:str]
    pgp:
        - created_at: "2026-09-01T20:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA5Atcb9kxMuUzHDK4iaz8YpYC3xPAmTjqWiCcuAvVgHgw
            hAEbgG3U0pBuOZ3wBQ4F1EfqXmM69I0T7wNgwT7V96CHngr2ht1Sz0lD6IngWQJN
            1GgBCQIQFJtE8WvDgbwlue1wGVXpxlSIP2qUu2jDGJGoIuhJGPPkPRMFmB3zCEjT
            sgXTy/U1jrKV3fWqEZfu3kCD3VM8FJjDqTnrNoyX5e4BnWzaYy9b4e7cDYrYf0na
            V0hjKXjPfnfZNA==
            =+y5Z
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rHj7CXHuVYI=,iv:lUI57GwBXOv/qNW3GqtErLXBjEwg8HTj57Wt+R7hrfs=,tag:rAfG52dq2Tka8mOYzh+VpA==,type:str]
    password: ENC[AES256_GCM,data:efJCBamQuRrxrX2Ok5bfqTtQKzrZpdLilwxyVPED680=,iv:8gJ3xTw6LOFqWEDV4oYWaplaujEuP5JuQrgTEK2UiYw=,tag:Q9+dnLaGLuGv+kiOlRTVUA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-01T20:47:29Z"
    mac: ENC[AES256_GCM,data:ImN6ZooIYAERfeIv9bsEllasw2wSlk5GIwS03o2ETkXVw7igL7VT6zqMyJKX14TziHpn7NTUROrfxH56TgBctA8m4x+YGDu/duE/DJYCEE9Fm5xuDPiG4iWcqlEPyOOsr394NSVGVK1ygaRgAYF7HAoMvUZoUiWkoqB7bNPADPs=,iv:OkhBezdkMKUAxsO1cPt2vU9IFRwmiMKv0jh18JQgCrs=,tag:hPRe+HT/K9b3tM2qxFcaLg==,type:str]
    pgp:
        - created_at: "2026-09-01T20:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA5Atcb9kxMuUzHDK4iaz8YpYC3xPAmTjqWiCcuAvVgHgw
            hAEbgG3U0pBuOZ3wBQ4F1EfqXmM69I0T7wNgwT7V96CHngr2ht1Sz0lD6IngWQJN
            1GgBCQIQFJtE8WvDgbwlue1wGVXpxlSIP2qUu2jDGJGoIuhJGPPkPRMFmB3zCEjT
            sgXTy/U1jrKV3fWqEZfu3kCD3VM8FJjDqTnrNoyX5e4BnWzaYy9b4e7cDYrYf0na
            V0hjKXjPfnfZNA==
            =+y5Z
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: jellystat-postgres-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:7rsKI/87HKkm,iv:CoWdweZmz5Y8RGtrjLy+0FWSgkM1797e+o4dB6yUZ2g=,tag:KL5Gn8AR9bfcH9jk2ODYPg==,type:str]
    password: ENC[AES256_GCM,data:55br1OEB8LSQR9paax7y1UjsOd1zwR7mGHh8cTq8fFqYbi8E9Rr0uEafYsQRnyrl,iv:8HBXHi2XCKAq0UaKe9cstTCONx5k5hxdAhL69BgHOXM=,tag:m9d1v3ETUuc9k3CQ/FLGGQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-01T20:47:29Z"
    mac: ENC[AES256_GCM,data:ImN6ZooIYAERfeIv9bsEllasw2wSlk5GIwS03o2ETkXVw7igL7VT6zqMyJKX14TziHpn7NTUROrfxH56TgBctA8m4x+YGDu/duE/DJYCEE9Fm5xuDPiG4iWcqlEPyOOsr394NSVGVK1ygaRgAYF7HAoMvUZoUiWkoqB7bNPADPs=,iv:OkhBezdkMKUAxsO1cPt2vU9IFRwmiMKv0jh18JQgCrs=,tag:hPRe+HT/K9b3tM2qxFcaLg==,type:str]
    pgp:
        - created_at: "2026-09-01T20:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdA5Atcb9kxMuUzHDK4iaz8YpYC3xPAmTjqWiCcuAvVgHgw
            hAEbgG3U0pBuOZ3wBQ4F1EfqXmM69I0T7wNgwT7V96CHngr2ht1Sz0lD6IngWQJN
            1GgBCQIQFJtE8WvDgbwlue1wGVXpxlSIP2qUu2jDGJGoIuhJGPPkPRMFmB3zCEjT
            sgXTy/U1jrKV3fWqEZfu3kCD3VM8FJjDqTnrNoyX5e4BnWzaYy9b4e7cDYrYf0na
            V0hjKXjPfnfZNA==
            =+y5Z
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
