apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qKLGN6Iq,iv:Xsp4LIEhQ1V3uubDYpEDf8VhRzXOI9yYjA7tEGdw8bg=,tag:djzf8mFSROAJxzwQuYGMqA==,type:str]
    password: ENC[AES256_GCM,data:nUTkrXif6FG6AoCIQSH1E6FhnaBc+TzPxvW/qDmfOCg=,iv:kkQjghIllH5+pTfX2TqZg2VI3n9pTA29FMfgDr9RsyE=,tag:wBlQT5cajcr4riaydqD7+A==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-21T21:30:29Z"
    mac: ENC[AES256_GCM,data:RiiTCLqvYt54If69au77DIRcLhY6vpKcxIOuYTtSDOOaSzoWslUUhyQlgDtZp74LoIEuCOhJ6TxlaG/1blcGIZaXKeRxH7IH32y7IaD+gl0agNJ3meZFhv17W1zaWLVqgGXn+NnlNj8JvUi2PsF3K9x9Nx3jeH7xVj+C0qcu7LY=,iv:6TJR5Qw+0YJgh/gw85c1CJ6QOULzrnlHav6ARolYjDg=,tag:ohVqbGLEi4rBKSCu1BRN5g==,type:str]
    pgp:
        - created_at: "2026-07-21T21:30:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAUcKQR/lkvW58yhC/p0xESEwOEcPwoTopfyuT72MKoyIw
            kVI6MR1nfMr39L3M2JKhB5vqnMxdHDX0atAns7BtGq+SbdjmYKoCdMrolhzQJbhQ
            1GYBCQIQtRgJ3smuZaL4h5XzT2Qxq68Hvnd1orNhV50wxJSRTAjc7Ru3Oa9TkWkq
            yGhXTfgE6RAnsiSIG9xE6GiklrafkYJz9izB4jl30MXwlE5kF6Bl+Y2XFEJGYk/P
            VWqXaHjKOMA=
            =GTWT
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:n7JfoZe+,iv:hTRXBLxdHA+4VubqHSqXQSc4FQUSJZ4P39+xyaQGRHs=,tag:M6Ye2BNW45U52ZIP0+PQGQ==,type:str]
    password: ENC[AES256_GCM,data:e7WF1EO3r0rsnkIQO2rLQVrNArI+M//NWT8Yz7AXt2M=,iv:t74MtT0QTpgtFDkwIX+X84w+/06jYs793ZyoQOjRTnA=,tag:EKYP+1jghBY37ELxbcorRA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-21T21:30:29Z"
    mac: ENC[AES256_GCM,data:RiiTCLqvYt54If69au77DIRcLhY6vpKcxIOuYTtSDOOaSzoWslUUhyQlgDtZp74LoIEuCOhJ6TxlaG/1blcGIZaXKeRxH7IH32y7IaD+gl0agNJ3meZFhv17W1zaWLVqgGXn+NnlNj8JvUi2PsF3K9x9Nx3jeH7xVj+C0qcu7LY=,iv:6TJR5Qw+0YJgh/gw85c1CJ6QOULzrnlHav6ARolYjDg=,tag:ohVqbGLEi4rBKSCu1BRN5g==,type:str]
    pgp:
        - created_at: "2026-07-21T21:30:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAUcKQR/lkvW58yhC/p0xESEwOEcPwoTopfyuT72MKoyIw
            kVI6MR1nfMr39L3M2JKhB5vqnMxdHDX0atAns7BtGq+SbdjmYKoCdMrolhzQJbhQ
            1GYBCQIQtRgJ3smuZaL4h5XzT2Qxq68Hvnd1orNhV50wxJSRTAjc7Ru3Oa9TkWkq
            yGhXTfgE6RAnsiSIG9xE6GiklrafkYJz9izB4jl30MXwlE5kF6Bl+Y2XFEJGYk/P
            VWqXaHjKOMA=
            =GTWT
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:jb8ESZ8=,iv:qsOmc6ZvKD+SgUo1oL3UUq+PJ5iq2SpBJUiCde66dkM=,tag:uztYr6CfQ7Sw7xxOOmwlmA==,type:str]
    password: ENC[AES256_GCM,data:jTKSxukACdmjoUvs2sJYZ2bLPl2/9/n8ZbcNZjhNxnQ=,iv:eNYYpVo/8yJeQ2FtaQxC/IAejYGDXjGYksSIQ7LO0k4=,tag:z4MRHMW68TLdM6euCZH4fA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-21T21:30:29Z"
    mac: ENC[AES256_GCM,data:RiiTCLqvYt54If69au77DIRcLhY6vpKcxIOuYTtSDOOaSzoWslUUhyQlgDtZp74LoIEuCOhJ6TxlaG/1blcGIZaXKeRxH7IH32y7IaD+gl0agNJ3meZFhv17W1zaWLVqgGXn+NnlNj8JvUi2PsF3K9x9Nx3jeH7xVj+C0qcu7LY=,iv:6TJR5Qw+0YJgh/gw85c1CJ6QOULzrnlHav6ARolYjDg=,tag:ohVqbGLEi4rBKSCu1BRN5g==,type:str]
    pgp:
        - created_at: "2026-07-21T21:30:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAUcKQR/lkvW58yhC/p0xESEwOEcPwoTopfyuT72MKoyIw
            kVI6MR1nfMr39L3M2JKhB5vqnMxdHDX0atAns7BtGq+SbdjmYKoCdMrolhzQJbhQ
            1GYBCQIQtRgJ3smuZaL4h5XzT2Qxq68Hvnd1orNhV50wxJSRTAjc7Ru3Oa9TkWkq
            yGhXTfgE6RAnsiSIG9xE6GiklrafkYJz9izB4jl30MXwlE5kF6Bl+Y2XFEJGYk/P
            VWqXaHjKOMA=
            =GTWT
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
