apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0w3LInNu,iv:wWqek+ZKj91pRckDlRL+9wmXdZuJK9YnY4NXmqwGglU=,tag:GSb5IxTzZTghfiNf20T7rw==,type:str]
    password: ENC[AES256_GCM,data:XU3DsgcR8uot2AeqHtZacHdmxcEiGcb6kdDhczlDqrs=,iv:CAXlwaxE/6dJhI+WVGXmnqbRioDStymnXIw4Mkx/FxE=,tag:diGeD4Ra7DSX7ol7SO+imA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-22T15:06:36Z"
    mac: ENC[AES256_GCM,data:Vy0Z8qD8F68QtSWLCyqhvAuVa/u/PbvJn57+f4WIimsJHpFDFDVes+gDHbpj30Cjy/5Rn/zbQd0HLAeAav3ChWKs4hk/rh8/Ud9YjlenOYjN7evYt49G36dVnN3ArW0nfLVTkdVX19GirpNpHcgHsWt+7hIVk8oHx659eVP7Ut8=,iv:Ao/nNBrjbEvxnk01nZUB9pputR6Ek+oNe6wtvVt2dX4=,tag:FNDyBatpRNgpdzYit6weWA==,type:str]
    pgp:
        - created_at: "2026-07-22T15:06:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAOaXXxY6QA8vaTm8BXz5MbrRwb9sxjsy3QH2nI+olMzIw
            +iv0odHwrLcTNv069K0tofhO8m2lIbbNw7C67zF/mtfdSyNxOqw6rtOLOYgb+/A+
            1GgBCQIQJJhTn3e1NWESnxGoWhxQ1I3WE9CwBOzrCwD71lvT7eh1F6+5CLgA/QWj
            eyuh3LPQz87xL+Y6xUQf1Bpq91IsbLtWOxEB1Als0Ddf4J5MQCovxPkPuVfHlPcp
            QSoIJ7Y00hYAog==
            =nVae
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kAe58iQR,iv:UgxNEQE1RQhc4O8H/wcaPkQ2GVkhhIDTphOfg4j/olY=,tag:K0CnSy5T6HVWyoM7uG0xkQ==,type:str]
    password: ENC[AES256_GCM,data:ejE1rDlLOJ1/YgAd6mbi2h5Ftm3D3SB7dhftakjLYiQ=,iv:dF01qEn2t7szszYYCt/e9EeAj6MEZLxmkOz0HNXpx5k=,tag:crKWagdv4UvVFbklFD2xSQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-22T15:06:36Z"
    mac: ENC[AES256_GCM,data:Vy0Z8qD8F68QtSWLCyqhvAuVa/u/PbvJn57+f4WIimsJHpFDFDVes+gDHbpj30Cjy/5Rn/zbQd0HLAeAav3ChWKs4hk/rh8/Ud9YjlenOYjN7evYt49G36dVnN3ArW0nfLVTkdVX19GirpNpHcgHsWt+7hIVk8oHx659eVP7Ut8=,iv:Ao/nNBrjbEvxnk01nZUB9pputR6Ek+oNe6wtvVt2dX4=,tag:FNDyBatpRNgpdzYit6weWA==,type:str]
    pgp:
        - created_at: "2026-07-22T15:06:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAOaXXxY6QA8vaTm8BXz5MbrRwb9sxjsy3QH2nI+olMzIw
            +iv0odHwrLcTNv069K0tofhO8m2lIbbNw7C67zF/mtfdSyNxOqw6rtOLOYgb+/A+
            1GgBCQIQJJhTn3e1NWESnxGoWhxQ1I3WE9CwBOzrCwD71lvT7eh1F6+5CLgA/QWj
            eyuh3LPQz87xL+Y6xUQf1Bpq91IsbLtWOxEB1Als0Ddf4J5MQCovxPkPuVfHlPcp
            QSoIJ7Y00hYAog==
            =nVae
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:QL7iOb8=,iv:HGLsQB6FH3gkA1375STz4eNAWe9/5tbg8BbiQIn1uWE=,tag:XQ/ZP8OTLjpERlpZlOMymw==,type:str]
    password: ENC[AES256_GCM,data:tLBkFoQcKfyHJOgcUfLbsi+3Hm+T/XCMkKh2XjMZjus=,iv:zvn1Z0pHh33hpKyXMtMgOWOCeaa9it3nlbw5ucmdN/Y=,tag:C+XkU9Wx5ed7duS7wCxpDA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-22T15:06:36Z"
    mac: ENC[AES256_GCM,data:Vy0Z8qD8F68QtSWLCyqhvAuVa/u/PbvJn57+f4WIimsJHpFDFDVes+gDHbpj30Cjy/5Rn/zbQd0HLAeAav3ChWKs4hk/rh8/Ud9YjlenOYjN7evYt49G36dVnN3ArW0nfLVTkdVX19GirpNpHcgHsWt+7hIVk8oHx659eVP7Ut8=,iv:Ao/nNBrjbEvxnk01nZUB9pputR6Ek+oNe6wtvVt2dX4=,tag:FNDyBatpRNgpdzYit6weWA==,type:str]
    pgp:
        - created_at: "2026-07-22T15:06:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAOaXXxY6QA8vaTm8BXz5MbrRwb9sxjsy3QH2nI+olMzIw
            +iv0odHwrLcTNv069K0tofhO8m2lIbbNw7C67zF/mtfdSyNxOqw6rtOLOYgb+/A+
            1GgBCQIQJJhTn3e1NWESnxGoWhxQ1I3WE9CwBOzrCwD71lvT7eh1F6+5CLgA/QWj
            eyuh3LPQz87xL+Y6xUQf1Bpq91IsbLtWOxEB1Als0Ddf4J5MQCovxPkPuVfHlPcp
            QSoIJ7Y00hYAog==
            =nVae
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fQZ98+JdfDM=,iv:pLwzuDXtr68hwYTNOAAXYZyP1LSx9lQgtdV7LRfaOr0=,tag:hXha/HrYEA98NgJp06xixg==,type:str]
    password: ENC[AES256_GCM,data:r4M8bAnuMJK+1WHZC1IeAAu7CWbpO8eSxqy9wCHOvYo=,iv:D8sjSBJuyw135vTV2YMwOOb5w9kWoEVGJBSJvr4aPno=,tag:2x8SO1VXQIqKTE3fkbUWTg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-22T15:06:36Z"
    mac: ENC[AES256_GCM,data:Vy0Z8qD8F68QtSWLCyqhvAuVa/u/PbvJn57+f4WIimsJHpFDFDVes+gDHbpj30Cjy/5Rn/zbQd0HLAeAav3ChWKs4hk/rh8/Ud9YjlenOYjN7evYt49G36dVnN3ArW0nfLVTkdVX19GirpNpHcgHsWt+7hIVk8oHx659eVP7Ut8=,iv:Ao/nNBrjbEvxnk01nZUB9pputR6Ek+oNe6wtvVt2dX4=,tag:FNDyBatpRNgpdzYit6weWA==,type:str]
    pgp:
        - created_at: "2026-07-22T15:06:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAOaXXxY6QA8vaTm8BXz5MbrRwb9sxjsy3QH2nI+olMzIw
            +iv0odHwrLcTNv069K0tofhO8m2lIbbNw7C67zF/mtfdSyNxOqw6rtOLOYgb+/A+
            1GgBCQIQJJhTn3e1NWESnxGoWhxQ1I3WE9CwBOzrCwD71lvT7eh1F6+5CLgA/QWj
            eyuh3LPQz87xL+Y6xUQf1Bpq91IsbLtWOxEB1Als0Ddf4J5MQCovxPkPuVfHlPcp
            QSoIJ7Y00hYAog==
            =nVae
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
