apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-s3-backup
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:vZk/IDX6KMR7ziBgogTSraiFY+BYNZ0ItgDKs1hRNfo=,iv:t0KU0qAQA+FXYaGU4hf7AYubFKJa8JPueFoE5qYvzFM=,tag:ZNtIJgqzN8rPTHS8xb+5og==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Vtnv/vzmuu8Fielqun44FrXUQ+ORv+IeWP6d5XUSYig=,iv:TRRiUkmHufD5VwrS0ZwgOaPYccwBCL0dFyNDlSnnaow=,tag:Bts4SKCalVStJXGUL1eDQA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-20T12:54:14Z"
    mac: ENC[AES256_GCM,data:vZ+ThL9V55TUoPu/4LDKOLDlfuOBmoW/ndyUCo7rQwHsZe3mqSTA5+Pn8fMy+45ig6EutErIWFrzWdU8TaAibF6BbaOeaR1GwRT0tFdd4v1tu0AA1GehqH00fKmDV9yJxoZTQOMtupXhkTB2da5/PqoluH5nz2zrmiF6iRxTtDQ=,iv:T78RpZYG8UUpiizleTCV4tgT0Kdcm8lVJbLFxpRL7Ls=,tag:YALtZ7Bfp/R4uH3aq7SgDQ==,type:str]
    pgp:
        - created_at: "2026-09-20T12:54:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAsgbOAgBeag/hyt4ppPLMjMXq9Zx31tJ0XYFZKl55/icw
            48GX7Y9pVQYy6orVW4Cpk4US9sRIr/K2WTw7MbQvXLgcKu0IcEvm4rklUbnvHM7A
            1GgBCQIQWjHushOI2ZC4hmgtj/nIa9j414eCI/tmV3imHsDhwCEOXf8jwIkmDOw2
            0N2Vmp+2UM61c89pUxYcNQu9CLTbsUK+2WPMN4lxC2CrLV1zRMhxEKQl78NleCk9
            aKZFErdo6jMYXA==
            =pGLU
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.3
