apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:7hrH1uM=,iv:dO1OJXKb/ZDPYXcPLYzYhiV9DqvNxx9F8xhkZb2t1CI=,tag:K9XeVN6NpYKnLLJPaM7WzA==,type:str]
    admin-password: ENC[AES256_GCM,data:omCzRTl55q3ZKIeeaDDt66DI4IL4LL+Vs43EphU+0KI=,iv:sCAsUFGMO8YQvjU3SOfpLKraC8nLuKUNqyFP2hGchos=,tag:n2q94E6ubVg3D+MhNRPVQQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-28T19:05:03Z"
    mac: ENC[AES256_GCM,data:KhcSqjyoAefec1NnJYO0KR7xmKAgE5Fr+fpfbEBuqkrcBUeRiTgeTkDwOzBYUOq4iIwOFhpqygCjcbaAxoH0J8uXRLVpQtpLaoc2Q3dH3rX+Y6TdH3x6Kkc9wXp2WQxPBGB9rgGMIN9qFuCMrMySITou+q5UVAJxLb5G9yKSfSg=,iv:PaqzEoSj4QgHvo7W+H+79VYtBZnrP/kicZC54kMdLFc=,tag:gC3c2iZjkUW4iQ3XSP3Gcg==,type:str]
    pgp:
        - created_at: "2026-07-28T19:05:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdASAJMkpLs5IV0UX865UApwM4/hc0YKv1wVluaX73E2Dww
            U+vAsOXQVZONPYUN11TivBj0Gp4+OLIuH4ZBKP18MYKi77upw9y11hJjEuqFnoDb
            1GgBCQIQAuLqLLo+jrEi/zLpGkRWPmFNMnHslxnGRrYLqujRaM/NvCSD0j6kQ3U2
            m+uhcdHrois7WEqZC4Vx7WM+y7sUTicrYJqzn1/PIj9eayCYs2oju0stfdasansM
            jU+TnvV5SVngCg==
            =tyvY
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-credentials
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:htmqOXA/eZUYB5StQTbOTK1ePoRESh5ld/8pnCmeS8aJ6edZog4Qj61uJncJGKsP3rRfjR4q4ahTgUnM1iVZpn3Bilso1mtRKj4tmORpcTmehSv4iseG7AB/AF84y+tnYmuycsBMoqGu/85IzVjvzrZ7QkTb0OAfu5qpOgYIL8g=,iv:6xw7rWk8gkT2phGHbogIlE8e/6vD+cUY3Ruhok/0shE=,tag:i3k1iwBxX2609loTnoXTLw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-28T19:05:03Z"
    mac: ENC[AES256_GCM,data:KhcSqjyoAefec1NnJYO0KR7xmKAgE5Fr+fpfbEBuqkrcBUeRiTgeTkDwOzBYUOq4iIwOFhpqygCjcbaAxoH0J8uXRLVpQtpLaoc2Q3dH3rX+Y6TdH3x6Kkc9wXp2WQxPBGB9rgGMIN9qFuCMrMySITou+q5UVAJxLb5G9yKSfSg=,iv:PaqzEoSj4QgHvo7W+H+79VYtBZnrP/kicZC54kMdLFc=,tag:gC3c2iZjkUW4iQ3XSP3Gcg==,type:str]
    pgp:
        - created_at: "2026-07-28T19:05:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdASAJMkpLs5IV0UX865UApwM4/hc0YKv1wVluaX73E2Dww
            U+vAsOXQVZONPYUN11TivBj0Gp4+OLIuH4ZBKP18MYKi77upw9y11hJjEuqFnoDb
            1GgBCQIQAuLqLLo+jrEi/zLpGkRWPmFNMnHslxnGRrYLqujRaM/NvCSD0j6kQ3U2
            m+uhcdHrois7WEqZC4Vx7WM+y7sUTicrYJqzn1/PIj9eayCYs2oju0stfdasansM
            jU+TnvV5SVngCg==
            =tyvY
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    version: 3.13.1
